### ISSUE TITLE
Question: Mapping Branchinfo to Source

### ISSUE THREAD

**Issue by paul1956** [tonerdo/coverlet#528] opened 2019-08-24 17:07 UTC
Is there any support for mapping BranchInfo information back to source, currently it maps to IL. Lines map to source but Offset is IL.

**Comment by SteveGilham** [comment] 2019-08-25 15:13
Root cause is that the debug information used to map back to the source is interested in statements, so gives line information for those.  At that level branches are but an implementation detail of how one gets from one statement to another.

One way or another, getting a line number involves finding the statement which spans the branch instruction and using its line information; in `coverlet`, that's done [here](https://github.com/tonerdo/coverlet/blob/70b3ef31dacf459dcb3ccd9b1ea831440c1928d0/src/coverlet.core/Symbols/CecilSymbolHelper.cs#L56), and eventually percolates its way to the `Line` property of the `BranchInfo` type, to be reflected in output reports..

**Comment by MarcoRossignoli** [comment] 2019-08-31 07:49
Thanks Steve!
@paul1956 if your question is answered feel free to close the issue

**Closed** 2019-09-12 07:28 UTC
Labels: question
