### ISSUE TITLE
ExcludeFromCodeCoverage ignore above properties

### ISSUE THREAD

**Issue by tsleegers** [tonerdo/coverlet#229] opened 2018-10-26 09:45 UTC
### Description

When excluding a propety from code coverage using de ExcludeFromCodeCoverage attribute this is ignored in the coverage result.

### Repro steps

Example code:
```csharp
public sealed class Euro : ICurrencyDefinition
{
	private const string currencyCode = "EUR";

	[ExcludeFromCodeCoverage]
	public string CurrencyCode
	{
		get
		{
			return currencyCode;
		}
	}

	[ExcludeFromCodeCoverage]
	public string Name
	{
		get { return "Euro"; }
	}

	[ExcludeFromCodeCoverage]
	public int NumberOfDecimals => 2;
}
```

All the above situations are marked as missing test coverage.

### Expected behavior

The properties are marked as covered.

### Actual behavior

The properties are not marked as missing code coverage.

### Known workarounds

Exclude the whole class from code coverage.

### Related information

* coverlet.msbuild Version: 2.3.1
* Visual Studio Version: Visual Studio Professional 2017 (15.8.7 and 15.9.0 Preview 3)
* Microsoft Test Execution Command Line Tool Version: 15.8.0

**Comment by akshaybheda** [comment] 2019-01-15 12:50
I don't think Coverlet supports this. You can see similar item #290 was closed as Won't fix

**Comment by SlowLogicBoy** [comment] 2019-01-15 13:01
@akshaybheda #290 issue is for assembly attributes.
@tsleegers [Dupe of #269 also this link contains a workaround](https://github.com/tonerdo/coverlet/issues/269#issuecomment-448548109)

**Comment by MarcoRossignoli** [comment] 2019-09-28 09:17
close for dup

**Closed by MarcoRossignoli** 2019-09-28 09:17 UTC
Labels: duplicate
