### ISSUE TITLE
Branch coverage with async calls

### ISSUE THREAD

**Issue by coryflucas** [tonerdo/coverlet#113] opened 2018-06-07 00:42 UTC
I have a project using EF Core with async methods that shows a branch at each await call. One of the branches always shows as uncovered.  I've created a sample repo that repoduces the problem [here](https://github.com/coryflucas/CoverletExample).  You can see the branch in the [coverage report](https://github.com/coryflucas/CoverletExample/blob/master/Test/coverage.json#L38-L47) but the [referenced line](https://github.com/coryflucas/CoverletExample/blob/master/Example/Example.cs#L18) does not have a branch.

Here is the output of `dotnet test`:
```
$ dotnet test /p:CollectCoverage=true
Build started, please wait...
Build completed.

Test run for /Users/clucas/Source/clucas/coverlet-test/Test/bin/Debug/netcoreapp2.1/Test.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.0845 Seconds

Calculating coverage result...
  Generating report '/Users/clucas/Source/clucas/coverlet-test/Test/coverage.json'

+---------+--------+--------+--------+
| Module  | Line   | Branch | Method |
+---------+--------+--------+--------+
| Example | 90.9%  | 50%    | 80%    |
+---------+--------+--------+--------+
```

I tired another example with `await HttpClient.GetAsync(...)` but that did not seem to produce the same issue so this doesn't appear to apply to all awaited calls.

**Comment by mgw854** [comment] 2018-06-07 02:41
I've noticed the same thing. My hunch (totally a guess here, so take it for what it's worth) is that the branch inserted by the compiler for awaiting code (such that you don't actually wait if the task has already completed) is being interpreted as a branch in your code.

*If* this is true, I don't think it's a meaningful distinction in 99+% of code. There are only two cases where I can think of that this matters. The first is using `.ConfigureAwait`, which doesn't do anything if the call was never awaited (such that you can accidentally pass on the captured state to a subsequent call that doesn't use `.ConfigureAwait`). The other is a timing bug where you expecting the current execution to yield, but it doesn't because the task was completed.

**Comment by abe545** [comment] 2018-06-27 15:41
We've noticed the same thing, and I put together a repro where `await Task.CompletedTask` causes it to report a partial branch: https://github.com/abe545/CoverletAwaitBranchCoverage/tree/master

**Comment by tonerdo** [comment] 2018-06-28 09:01
Thanks for reporting this guys. I'm currently working on general improvements to the coverage logic so will add this to the list. Thanks for the test project @abe545

**Comment by rmlira** [comment] 2018-08-29 17:42
+1

**Comment by sugarjig** [comment] 2019-01-25 20:17
I'm seeing this issue still in version 2.5.1 (that's the version number in Nuget).

**Comment by MarcoRossignoli** [comment] 2019-01-26 08:06
@sugarjig can you provide a repro?

**Comment by soljarka** [comment] 2019-04-29 09:21
Same with 2.6.0

**Comment by MarcoRossignoli** [comment] 2019-04-29 09:32
@soljarka can you provide a repro?

**Comment by Rjae** [comment] 2019-08-29 18:20
I don't know if this is old news, but I think I figured out a way through. By adding a simple continuation I was able to get Coverlet to consider all branches hit. For example:

`return await _service.SendAsync(command).ContinueWith(x => x.Result);`

I hope that helps others.

**Comment by MarcoRossignoli** [comment] 2019-08-29 18:50
Thanks @Rjae for the comment...can you provide a repro of the issue (I mean a piece of code without continuation that leads to invalid async branch coverage)

**Comment by Rjae** [comment] 2019-08-30 19:33
Sure thing bro...literally the same line without the *ContinueWith*. So...

`return await _service.SendAsync(command);`

I've used same approach in several more lines with same success.

**Comment by MarcoRossignoli** [comment] 2019-08-30 20:22
Thanks I'll take a look asap

**Comment by Rjae** [comment] 2019-08-30 20:25
Wow...thanks! Additional "discovery": ContinueWith does not appear to solve the coverage reporting for Task (void) lines, only for Task<T> lines.

**Comment by Rjae** [comment] 2019-08-31 11:14
BTW, I'm looking for a temporary ignore for these cases. I've tried following attribute-excludes: `GeneratedCodeAttribute,CompilerGeneratedAttribute,AsyncStateMachineAttribute` but no luck. @MarcoRossignoli if you know a way to ignore these cases from analysis I'd be interested to know.

**Comment by MarcoRossignoli** [comment] 2019-08-31 12:41
@Rjae add `CompilerGeneratedAttribute` should work on next version thank's to https://github.com/tonerdo/coverlet/pull/477 but it was merged on 3 July and last verson was released 1 July.
For the moment you can try to doogfood coverlet using this guide https://github.com/tonerdo/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md 
When we'll release next version you can revert.
Sorry but for the moment I don't have better choice...we need to fix issue with async and do a release 😞  so for the moment you can skip using dogfooding and after using new release.

**Comment by Rjae** [comment] 2019-08-31 22:09
@MarcoRossignoli again, thanks! Will watch for async fix.

**Closed** 2019-09-23 09:00 UTC
Labels: bug, tenet-coverage

**Comment by brad** [comment] 2022-02-24 22:34
Seeing this in the latest coverlet (3.1.2). Using Cake.Coverlet 2.5.4. Happens with all the HttpClient async requests I'm using
- GetAsync
- PostAsync
- PustAsync

**Comment by brad** [comment] 2022-02-24 22:37
Another workaround I found is to change `await httpClient.GetAsync(url)` to `httpClient.GetAsync(url).Result`

**Comment by petli** [comment] 2022-02-25 09:43
Hi @brad, thanks for the report. Can you create a new issue on it, to make it possible to track? If you have a small example reproducing the issue it's really useful too.

**Comment by nycdotnet** [comment] 2022-02-25 15:04
@brad note - your suggestion also changes the functionality of the code with regards to asynchrony.  Depending on the performance requirements of your code, it may be a really bad tradeoff to work around a coverage issue.

https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#avoid-using-taskresult-and-taskwait

**Comment by brad** [comment] 2022-02-25 16:30
@nycdotnet Thanks for the heads up @petli Sure, no problem

**Comment by brad** [comment] 2022-02-25 16:44
@petli Is there a forum/chat group to get support? I'm testing this with a minimal application and am _not_ able to reproduce the issue there so clearly I am doing something wrong ☹️

**Comment by petli** [comment] 2022-02-25 18:16
@brad There's a discussion forum here: https://github.com/coverlet-coverage/coverlet/discussions
