### ISSUE TITLE
Test run fails when `Oracle.ManagedDataAccess` is added

### ISSUE THREAD

**Issue by henrihs** [tonerdo/coverlet#189] opened 2018-09-07 18:44 UTC
First of all I want to thank you for the amazing tool you've made!

I've got this issue in a project which targets full framework (4.6.1), where the test run writes out this error during execution:

```C:\Users\user\.nuget\packages\coverlet.msbuild\2.3.0\build\netstandard2.0\coverlet.msbuild.targets(16,5): error : Invalid directory size. [C:\work\temp\demotest\demotest.csproj]```

I've been able to isolate the problem, and it seems to only occur when I add a reference to the package `Oracle.ManagedDataAccess`. The issue is not present when targeting `netstandard2.0/netcoreapp2.1` and using `Oracle.ManagedDataAccess.Core`, but since this package still is in beta we're not able to ship software relying on it, yet.

### Steps to reproduce

Execute the following lines (was performed in wsl-terminal). I've truncated the classes to single lines to make it easier to copy-paste.

```shell
mkdir temp && cd temp
dotnet new classlib -n demo
dotnet new xunit -n demotest
dotnet add demotest/ reference demo/demo.csproj

sed -i 's\netcoreapp2.1\net461\' demotest/demotest.csproj
sed -i 's\netstandard2.0\net461\' demo/demo.csproj

dotnet add demotest/ package coverlet.msbuild

echo 'namespace demo { public class TestableClass { public static int Answer() { return 42; } } }' > demo/TestableClass.cs
echo 'using demo; using Xunit; namespace demotest { public class TestClass { [Fact] public void Test() { Assert.Equal(42, TestableClass.Answer()); } } }' > demotest/TestClass.cs

dotnet test demotest/ /p:collectcoverage=true
echo Return code $?

dotnet add demo/ package Oracle.ManagedDataAccess
dotnet test demotest/ /p:collectcoverage=true
echo Return code $?
```

### Issue

The first test run is successfully executed, and returns exit code 0.
As you can see, the latter test run writes out the error message mentioned in the top after build, before proceeding (and successfully executing) with the test run, and returns exit code 1.

**Comment by tonerdo** [comment] 2018-09-07 19:02
Hey @henrihs, at this time Coverlet only works with .NET Core and not the full framework. Bringing it to the full framework is definitely something I've thought about and so far there's been very little in the way of demand/ROI.

Opencover and AltCover might be alternatives to explore

**Comment by tonerdo** [comment] 2018-09-07 21:43
Well there's nothing _technically_ stopping Coverlet from working on .NET Framework, it's just not a scenario I've tested so there are definitely gonna be some kinks here and there. 

However, since `Oracle.ManagedDataAccess` is a public package I'll try to reproduce this locally and come up with a solution

**Comment by SteveGilham** [comment] 2018-09-09 12:32
I've had a quick look at this, and

1. It looks to be purely cosmetic with coverage of the system under test being generated OK at the end of the day
2. The latest version of Oracle.ManageDataAccess.dll (which is of course copied to the output directory for a full framework build) fails to decompile in the latest ILSpy (it raises an exception reading the debug header with an invalid length) -- this may be related
3. As the Oracle package contains no .pdb files, AltCover doesn't even try to instrument that assembly, and raises no exception in an equivalent to the repro steps given above.
```
dotnet add demotest/ package altcover
dotnet test demotest/ /p:AltCover=true -v m
```

**Comment by MarcoRossignoli** [comment] 2019-09-28 08:36
This should be resolved in last version where we skip to instrument dll without pdb or local sources(embedded or not).
Feel free to reopen if needed.

**Closed by MarcoRossignoli** 2019-09-28 08:36 UTC
