### ISSUE TITLE
Display combined coverage even when Threshold is not exceeded

### ISSUE THREAD

**Issue by ptupitsyn** [tonerdo/coverlet#95] opened 2018-05-13 21:08 UTC
`Threshold` allows us to fail a build when coverage drops beyond certain percentage.
This percentage is combined from all modules involved.

It would be great to see this percentage even when `Threshold` is not used or exceeded.

**Comment by StephenMP** [comment] 2018-05-14 14:04
Hi @ptupitsyn, If I understand your suggestion correctly, this is already implemented, there just hasn't been a new release containing this new code yet :)

The new code will show you something like the following on every test run:

```
+---------------+--------+--------+--------+
| Module        | Line   | Branch | Method |
+---------------+--------+--------+--------+
| coverlet.core | 90.6%  | 86.7%  | 93.8%  |
+---------------+--------+--------+--------+
```

**Comment by ptupitsyn** [comment] 2018-05-14 18:16
`Line`, `Branch` and `Method` details are awesome!

I am talking about something like this though:

```
| Module                  | Coverage |
|-------------------------|----------|
| A.B.C                   | 80.5%    |
| Foo.Bar                 | 50.0%    |
| Baz.Qux                 | 60.0%    |
|-------------------------|----------|
| Average                 | 63.5%    |
```

Because when I set `/p:Threshold`, I get errors like

`Overall average coverage '63.5%' is lower than specified threshold '70%'`.
So this number, `63.5%`, is only visible when there is a Threshold error.

**Comment by StephenMP** [comment] 2018-05-20 19:42
Oh I see what you mean. I think this is a duplicate of #29

**Comment by tonerdo** [comment] 2018-06-12 08:10
Available in relase: https://www.nuget.org/packages/coverlet.msbuild/2.0.1

**Closed by tonerdo** 2018-06-12 08:10 UTC
