### ISSUE TITLE
MergeWith is not working in global tool

### ISSUE THREAD

**Issue by priyanka1112** [tonerdo/coverlet#624] opened 2019-11-27 11:51 UTC
Hi, I am using coverlet 1.6.0 version and in my solution there are multiple test project but mergewith is not working

I am using below:

Coverlet "D:\Project\proj1.Test\bin\Debug\netcoreapp2.2\proj1.Test.dll" --target "dotnet" --targetargs "test "D:\Project\proj1.Test" --no-build"
Coverlet "D:\Project\proj2.Test\bin\Debug\netcoreapp2.2\proj2.Test.dll" --target "dotnet" --targetargs "test "D:\Project\proj2.Test" --no-build" --merge-with=”D:\Project\Coverage.json”
Coverlet "D:\Project\proj3.Test\bin\Debug\netcoreapp2.2\proj3.Test.dll" --target "dotnet" --targetargs "test "D:\Project\proj2.Test" --no-build" --no-build" --merge-with=”D:\Project\Coverage.json” --format opencover

**Comment by MarcoRossignoli** [comment] 2019-11-27 12:11
Can you provide a repro?I did some test with test on codebase and seem work, my workflow
```bash
cd C:\git\coverlet\Documentation\Examples\MSBuild\MergeWith
dotnet build
coverlet XUnitTestProject1\bin\Debug\netcoreapp2.0\XUnitTestProject1.dll --target "dotnet" --targetargs "test C:\git\coverlet\Documentation\Examples\MSBuild\MergeWith\XUnitTestProject1 --no-build"
coverlet XUnitTestProject2\bin\Debug\netcoreapp2.0\XUnitTestProject2.dll --target "dotnet" --targetargs "test C:\git\coverlet\Documentation\Examples\MSBuild\MergeWith\XUnitTestProject2 --no-build" --merge-with "C:\git\coverlet\Documentation\Examples\MSBuild\MergeWith\coverage.json"
coverlet XUnitTestProject3\bin\Debug\netcoreapp2.0\XUnitTestProject3.dll --target "dotnet" --targetargs "test C:\git\coverlet\Documentation\Examples\MSBuild\MergeWith\XUnitTestProject3 --no-build" --merge-with "C:\git\coverlet\Documentation\Examples\MSBuild\MergeWith\coverage.json" --format opencover
```
And I get `C:\git\coverlet\Documentation\Examples\MSBuild\MergeWith\coverage.opencover.xml`
```xml
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession>
  <Summary numSequencePoints="9" visitedSequencePoints="9" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="3" numClasses="3" visitedMethods="3" numMethods="3" />
  <Modules>
    <Module hash="D62D8A89-5F2A-4395-B7B5-6E4A4B9AD217">
      <ModulePath>ClassLibrary3.dll</ModulePath>
      <ModuleTime>2019-11-27T12:08:27</ModuleTime>
      <ModuleName>ClassLibrary3</ModuleName>
      <Files>
        <File uid="1" fullPath="C:\git\coverlet\Documentation\Examples\MSBuild\MergeWith\ClassLibrary3\Class3.cs" />
      </Files>
      <Classes>
        <Class>
          <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="1" numClasses="1" visitedMethods="1" numMethods="1" />
          <FullName>ClassLibrary3.Class3</FullName>
          <Methods>
            <Method cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="100" branchCoverage="100" isConstructor="False" isGetter="False" isSetter="False" isStatic="True">
              <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="1" numMethods="1" />
              <MetadataToken />
              <Name>System.Int32 ClassLibrary3.Class3::Method()</Name>
              <FileRef uid="1" />
              <SequencePoints>
                <SequencePoint vc="1" uspid="8" ordinal="0" sl="8" sc="1" el="8" ec="2" bec="0" bev="0" fileid="1" />
                <SequencePoint vc="1" uspid="9" ordinal="1" sl="9" sc="1" el="9" ec="2" bec="0" bev="0" fileid="1" />
                <SequencePoint vc="1" uspid="10" ordinal="2" sl="10" sc="1" el="10" ec="2" bec="0" bev="0" fileid="1" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint vc="3" uspid="0" p8:type="SequencePoint" ordinal="0" offset="0" sc="0" sl="8" ec="1" el="10" bec="0" bev="0" fileid="1" xmlns:p8="xsi" />
            </Method>
          </Methods>
        </Class>
      </Classes>
    </Module>
    <Module hash="BCD05959-F8A3-431F-8DAE-B39B40E61315">
      <ModulePath>ClassLibrary2.dll</ModulePath>
      <ModuleTime>2019-11-27T12:08:27</ModuleTime>
      <ModuleName>ClassLibrary2</ModuleName>
      <Files>
        <File uid="2" fullPath="C:\git\coverlet\Documentation\Examples\MSBuild\MergeWith\ClassLibrary2\Class2.cs" />
      </Files>
      <Classes>
        <Class>
          <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="1" numClasses="1" visitedMethods="1" numMethods="1" />
          <FullName>ClassLibrary2.Class2</FullName>
          <Methods>
            <Method cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="100" branchCoverage="100" isConstructor="False" isGetter="False" isSetter="False" isStatic="True">
              <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="1" numMethods="1" />
              <MetadataToken />
              <Name>System.Int32 ClassLibrary2.Class2::Method()</Name>
              <FileRef uid="2" />
              <SequencePoints>
                <SequencePoint vc="1" uspid="8" ordinal="0" sl="8" sc="1" el="8" ec="2" bec="0" bev="0" fileid="2" />
                <SequencePoint vc="1" uspid="9" ordinal="1" sl="9" sc="1" el="9" ec="2" bec="0" bev="0" fileid="2" />
                <SequencePoint vc="1" uspid="10" ordinal="2" sl="10" sc="1" el="10" ec="2" bec="0" bev="0" fileid="2" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint vc="3" uspid="0" p8:type="SequencePoint" ordinal="0" offset="0" sc="0" sl="8" ec="1" el="10" bec="0" bev="0" fileid="2" xmlns:p8="xsi" />
            </Method>
          </Methods>
        </Class>
      </Classes>
    </Module>
    <Module hash="67FD7FF8-E2B2-49DC-A11C-43E8CCE910B4">
      <ModulePath>ClassLibrary1.dll</ModulePath>
      <ModuleTime>2019-11-27T12:08:27</ModuleTime>
      <ModuleName>ClassLibrary1</ModuleName>
      <Files>
        <File uid="3" fullPath="C:\git\coverlet\Documentation\Examples\MSBuild\MergeWith\ClassLibrary1\Class1.cs" />
      </Files>
      <Classes>
        <Class>
          <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="1" numClasses="1" visitedMethods="1" numMethods="1" />
          <FullName>ClassLibrary1.Class1</FullName>
          <Methods>
            <Method cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="100" branchCoverage="100" isConstructor="False" isGetter="False" isSetter="False" isStatic="True">
              <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="1" numMethods="1" />
              <MetadataToken />
              <Name>System.Int32 ClassLibrary1.Class1::Method()</Name>
              <FileRef uid="3" />
              <SequencePoints>
                <SequencePoint vc="1" uspid="8" ordinal="0" sl="8" sc="1" el="8" ec="2" bec="0" bev="0" fileid="3" />
                <SequencePoint vc="1" uspid="9" ordinal="1" sl="9" sc="1" el="9" ec="2" bec="0" bev="0" fileid="3" />
                <SequencePoint vc="1" uspid="10" ordinal="2" sl="10" sc="1" el="10" ec="2" bec="0" bev="0" fileid="3" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint vc="3" uspid="0" p8:type="SequencePoint" ordinal="0" offset="0" sc="0" sl="8" ec="1" el="10" bec="0" bev="0" fileid="3" xmlns:p8="xsi" />
            </Method>
          </Methods>
        </Class>
      </Classes>
    </Module>
  </Modules>
</CoverageSession>
```

**Comment by MarcoRossignoli** [comment] 2019-12-02 18:51
Any news?

**Comment by StefanOssendorf** [comment] 2019-12-20 08:45
I try to use MergeWith with the VS-Integration but no luck so far. Is this related or should I create a new issue?

Some mor infos:
I get the files per test-project but not a merged one. I have derived an example from your HelloWorld-Docu solution with two test projects and a settings file. [https://github.com/StefanOssendorf/Coverlet_Mwe_MergeWithNotWorking](url)

**Comment by MarcoRossignoli** [comment] 2019-12-20 09:04
Please open a new issue this one is related to .net tool a different workflow

**Comment by MarcoRossignoli** [comment] 2020-01-02 23:23
@priyanka1112 any news on this?

**Comment by MarcoRossignoli** [comment] 2020-01-22 11:17
Close for stale conversation after two ping.
Feel free to re-open if needed.

**Closed by MarcoRossignoli** 2020-01-22 11:17 UTC
Labels: driver-console, needs more info

**Comment by sudharshan1992** [comment] 2021-03-19 22:35
@MarcoRossignoli I'm using coverlet.console (version '3.0.3') to run code coverage for multiple test projects via bitbucket pipeline. 

coverlet /opt/atlassian/pipelines/agent/build/Tests.CommandProxy.Shared/bin/Release/netcoreapp3.1/Tests.CommandProxy.Shared.dll --target "dotnet" --targetargs "test /opt/atlassian/pipelines/agent/build/Tests.CommandProxy.Shared --no-build"
coverlet /opt/atlassian/pipelines/agent/build/CommandProxy.Unit.Tests/bin/Release/netcoreapp3.1/CommandProxy.Unit.Tests.dll --target "dotnet" --targetargs "test /opt/atlassian/pipelines/agent/build/CommandProxy.Unit.Tests --no-build" --merge-with "/opt/atlassian/pipelines/agent/build/coverage.json"
coverlet /opt/atlassian/pipelines/agent/build/CommandProxy.Integration.Tests.Core/bin/Release/netcoreapp3.1/CommandProxy.Integration.Tests.Core.dll --target "dotnet" --targetargs "test /opt/atlassian/pipelines/agent/build/CommandProxy.Integration.Tests.Core --no-build" --merge-with "/opt/atlassian/pipelines/agent/build/coverage.json"
coverlet /opt/atlassian/pipelines/agent/build/CommandProxyCore.Unit.Tests/bin/Release/netcoreapp3.1/CommandProxyCore.Unit.Tests.dll --target "dotnet" --targetargs "test /opt/atlassian/pipelines/agent/build/CommandProxyCore.Unit.Tests --no-build" --merge-with "/opt/atlassian/pipelines/agent/build/coverage.json" --format opencover

But I keep getting the error: **The argument /opt/atlassian/pipelines/agent/build/Tests.CommandProxy.Shared/bin/Debug/netcoreapp3.1/Tests.CommandProxy.Shared.dll is invalid. Please use the /help option to check the list of valid arguments.**

![image](https://user-images.githubusercontent.com/38304234/111848585-9d5ebb00-88c8-11eb-8bf9-aa5fd51ddacf.png)

Kindly help! Thanks!

**Comment by daveMueller** [comment] 2021-03-20 01:21
Thanks for reporting. First of all, can you open a new issue for this? 

Somehow I don't think this issue is caused by coverlet because the error appears when executing ```dotnet test```.
Can you try to run the test without coverage ```dotnet test /opt/atlassian/pipelines/agent/build/Tests.CommandProxy.Shared --no-build```? Can you reproduce this locally and if yes could you provide a repro?

**Comment by sudharshan1992** [comment] 2021-03-20 16:25
@daveMueller I got it to work when I don't have the "Release" configuration tag in dotnet build. And when I have the release tag, it fails (See both screenshots below)

![image](https://user-images.githubusercontent.com/38304234/111876553-7baf1380-895c-11eb-94b8-45dce97ef520.png)

![image](https://user-images.githubusercontent.com/38304234/111876658-00019680-895d-11eb-9cfd-aeb561a25258.png)

The dotnet test /opt/atlassian/pipelines/agent/build/Tests.CommandProxy.Shared --no-build fails when I have the "Release" tag and passes when I don't (see screenshots below) 

![image](https://user-images.githubusercontent.com/38304234/111876836-d1d08680-895d-11eb-949b-858b91e861f1.png)

![image](https://user-images.githubusercontent.com/38304234/111876896-f6c4f980-895d-11eb-8af1-74a87c3d880e.png)

Probably i'm using it wrong??

PS: I can create a new ticket if you'd like to, as this is not pertaining to this thread. Thanks!

**Comment by daveMueller** [comment] 2021-03-21 01:16
You could try to use vstest instead (```dotnet vstest /opt/at....```). Or you could try to specify the project file (```dotnet test /opt/at.../abc.csproj```).
If it is really only one assembly you could also try to explicitly reference the assembly (```dotnet test /opt/at.../abc.test..dll```). 

I don't think you are using it wrong. According to the dotnet test documentation this should work. Maybe the release build is missing some reference. @MarcoRossignoli Any other ideas?

Nevertheless this is not related to MergeWith and thus it would be cool if you open a new issue for this. 
If all the ideas don't help, we can track the issue better.

**Comment by MarcoRossignoli** [comment] 2021-03-21 10:04
Could be an escape issue?
![image](https://user-images.githubusercontent.com/7894084/111900850-1aa73e80-8a35-11eb-8fa2-6dc193e6aae0.png)

**Comment by sudharshan1992** [comment] 2021-03-22 06:37
@MarcoRossignoli @daveMueller 

I was able to fix the issue, I forgot the _--configuration Release_ during _dotnet test_

_**dotnet test /opt/atlassian/pipelines/agent/build/Tests.CommandProxy.Shared/bin/Release/netcoreapp3.1/Tests.CommandProxy.Shared.dll --no-build --configuration Release**_ 

I'm not opening an another issue. Thanks for all the help :)
