### ISSUE TITLE
Possibility to merge different  test project results into operncover format

### ISSUE THREAD

**Issue by balage90** [tonerdo/coverlet#196] opened 2018-09-21 09:15 UTC
Currently if i understand correctly the /p:mergeWith paramter only works in case of Json format.
I'd like to have results in opencover output due to sonarqube alanizis.

We have multiple test for different csproj,-s in our project.

e.g.: dotnet test someProject.csproj --configuration debug /p:CollectCoverage=true  /p:CoverletOutput=/TestResultOutput/Coverlet/SomeProject_Merge.xml /p:MergeWith=/TestResultOutput/Coverlet/Merge_All.xml /p:CoverletOutputFormat=opencover

Or if it already possible please correct me.

Br

Balázs

**Comment by petli** [comment] 2018-09-21 12:55
If you don't need a merged opencover file, but just a merged coverage report of some kind, you can use https://github.com/danielpalme/ReportGenerator to read multiple opencover.xml files and produce a single report.

**Comment by petli** [comment] 2018-09-21 12:55
If you don't need a merged opencover file, but just a merged coverage report of some kind, you can use https://github.com/danielpalme/ReportGenerator to read multiple opencover.xml files and produce a single report.

**Comment by petli** [comment] 2018-09-21 12:55
If you don't need a merged opencover file, but just a merged coverage report of some kind, you can use https://github.com/danielpalme/ReportGenerator to read multiple opencover.xml files and produce a single report.

**Comment by tonerdo** [comment] 2018-09-27 15:00
Hi @balage90, you can simply merge all your coverlet json result files and output them in OpenCover format

**Comment by tonerdo** [comment] 2018-09-27 17:01
Here's an example:

```csharp
dotnet test /p:CollectCoverage=true /p:MergeWith="./other/result.json" /p:CoverletOutputFormat="opencover"
```

**Comment by pape77** [comment] 2018-09-28 11:58
I'm trying to run this but since i'm doing a dotnet test on the solution which detects what to test, it will say that the result.json file does not exist, as it doesn't create it the first time it runs the test for one of the projects in the solution :/
I'm forced to run tests for one test proj and then run the test solution with the merge param, which results in two steps and double testing a project :/

**Comment by balage90** [comment] 2018-10-01 09:06
Yes i exactly wanted to do something similar, so for the first project test execution generates a merge.json and then i will try to use the MergeWith parameter at the second execution where I am referencing the merge.json from the previous run. And so on with the rest of the test projects. But sitll dont know how and wen should i able to generate opencover output since the previous repots are in Json format and not opencover.

**Comment by pape77** [comment] 2018-10-01 14:54
@balage90 you should be able to do it in the final dotnet test excecution. So you have:

1- The first one just doing a dotnet test and generating the first coverage.json file
2- Subsequent n-1 dotnet test using the mergeWith parameter referencing the just created coverage.json file
3- Last one should also use mergeWith BUT ALSO ```/p:CoverletOutputFormat=opencover``` in order to generate the final opencover.xml file that you want, based on the merged coverage.json.

You can also just do a dotnet test on the first one to generate the coverage.json and then do a dotnet test on the solution with the opencover output param, to generate all the subsequent merges and the final opencover.xml generation  (it's all in the issue #203)

The problem is, however, the one I mentioned in the issue I opened. I made a pr for fixing that, but has to be reviewed by @tonerdo yet

Let me know your findings, and if you face the same problem i had (since you use more than one test project too :) )

**Comment by balage90** [comment] 2018-10-01 20:41
@pape77 Thanks a lot will try it out tomorrow and let you know the result.

**Comment by pape77** [comment] 2018-10-03 15:06
@balange90 And? And? :P

**Comment by 8** [comment] 2018-10-16 11:50
> I'm trying to run this but since i'm doing a dotnet test on the solution which detects what to test, it will say that the result.json file does not exist, as it doesn't create it the first time it runs the test for one of the projects in the solution :/

I am struggling with the same problem.
I've worked around that by creating an (almost) empty .json file to start with:

```
# create the testresults folder
$TestResultFolder = (Get-Location).Path + '\TestResults\'
New-Item -Path $TestResultFolder -ItemType Directory -Force

# create the initial file that coverlet needs for merging
$CoverletOutput = $TestResultFolder + 'coverage.json'
Set-Content -Path $CoverletOutput -Value "{}"
```

and then I can create a combined file like so:
```
$cmd = "dotnet test --no-build -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=json /p:MergeWith=$CoverletOutput /p:CoverletOutput=$CoverletOutput src\Solution.sln --filter FullyQualifiedName~Unit --logger=trx -r $TestResultFolder"
Invoke-Expression $cmd
```

Now it's only 1 run over the whole solution and I got a combined `coverage.json` - but I am stuck now converting that file to opencover without supplying a test project.

Anybody got an idea? I haven't found any straightforward way to test a solution and produce a single coverage report.

Take care,
Martin

**Comment by pape77** [comment] 2018-10-16 15:18
Hi @8 in #203 I create a opencover report.
You can replace the first run i make with your empty json file generation and it should work. 
Cheers!

**Comment by 8** [comment] 2018-10-16 18:51
Hi @pape77, 
thanks for the reply!

I finally solved my problem doing what @petli  suggested:
1) I switched back to generating an opencover report per project in the solution by pointing coverlet at the solution file.
2) Then collect them using powershell and pass them as a single argument to reportgenerator which can handle multiple entries and combine them in a single report.

Take care,
-Martin

**Comment by pape77** [comment] 2018-10-16 21:08
@8 ah I don't use the report generator or poweshell. I want coverlet to generate the merged coverage. Then it can be used for whatever. 
That's what I'm aiming for with the pr ;)

But good you found a way for your case

Cheers

**Comment by vlef** [comment] 2018-10-18 18:37
My pull request #220 is a quick fix that should allow for a way to accomplish this (see my comment), if someone's willing to test it.

**Comment by vlef** [comment] 2019-02-01 21:43
Since #220 has been released, this issue should be closed. It is now possible to merge in other formats than json. Exlained in more details in issue #220

**Closed** 2019-02-23 18:45 UTC
