### ISSUE TITLE
Incorrect coverage reporting 🐛

### ISSUE THREAD

**Issue by atifaziz** [tonerdo/coverlet#7] opened 2018-03-22 14:23 UTC
The coverage report for 87135a5d0c3c5a27db83509fba01774dd20201d9 claims that [`DictionaryExtensions.cs` has 75% coverage](https://coveralls.io/builds/16102295/source?filename=/src/coverlet.core/Extensions/DictionaryExtensions.cs). It only has one method:

https://github.com/tonerdo/coverlet/blob/87135a5d0c3c5a27db83509fba01774dd20201d9/src/coverlet.core/Extensions/DictionaryExtensions.cs#L7-L14

According to the report, lines 9, 10 and 13 are covered but not line 12 (thus the 75%). How can 13 be covered but not 12? Is this a bug or am I misreading something? The only test for this method…

https://github.com/tonerdo/coverlet/blob/87135a5d0c3c5a27db83509fba01774dd20201d9/test/coverlet.core.tests/Extensions/DictionaryExtensionsTests.cs#L10-L17

…seems to cover it 100%.

**Comment by tonerdo** [comment] 2018-03-22 14:24
@atifaziz I have noticed this little kinks here and there. Currently trying to find the root cause, intend to have it fixed by this weekend

**Comment by OneCyrus** [comment] 2018-03-22 19:45
we saw similar issues here. some lines between covered ones where missing where it wasn't possible to branch.

**Comment by tonerdo** [comment] 2018-03-22 23:50
@OneCyrus @atifaziz This issue has been fixed in #10. It was actually a pretty straightforward fix and a good side effect is it sets the foundation for branch coverage support. This fix will be in a new NuGet package I'll release this weekend, in the future I'll setup a nightly CI package publish so improvements can get out faster.

Cheers

**Comment by atifaziz** [comment] 2018-03-23 17:07
@tonerdo Thanks and looking forward to trying out the new package soon after it's up.

**Comment by tonerdo** [comment] 2018-03-26 10:33
@atifaziz New NuGet package release: https://www.nuget.org/packages/coverlet.msbuild/1.0.1

**Comment by tonerdo** [comment] 2018-03-26 10:35
@OneCyrus lemme know if the new NuGet package also fixes the issues you were seeing regarding coverage accuracy

**Comment by OneCyrus** [comment] 2018-03-26 13:17
it improved here but there are still some missing parts. e.g.:

![image](https://user-images.githubusercontent.com/7747800/37908480-afd875c0-3108-11e8-877d-8d8f86596487.png)

**Comment by tonerdo** [comment] 2018-03-26 13:18
Thanks for pointing that out. Any other examples you can show?

**Comment by OneCyrus** [comment] 2018-03-27 14:21
here's another example:

![image](https://user-images.githubusercontent.com/7747800/37973418-b4d9829e-31da-11e8-8342-81d66e5b381b.png)

it looks like it doesn't like LINQ. all the missing things I saw are related to LINQ.

**Comment by tonerdo** [comment] 2018-03-27 14:53
I'm not surprised, the IL the compiler generates for LINQ is horrendous. I'll take a closer look, thanks

**Comment by tonerdo** [comment] 2018-04-16 13:57
@OneCyrus kindly use the latest NuGet bits which has branch coverage support and see if this helps fix this issue. Thanks

**Closed** 2018-05-01 20:49 UTC
